global:
  scrape_interval:     2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: nvml
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:8000']
